### ISSUE TITLE
Add support to Conventional Commits automatically with Commitzen

### ISSUE THREAD

**Issue by omariosouto** [skynexui/core#22]
**Why**
Because will make easier ensure that all commits are being done thinking in Semantic Release

**How**
We could just use Husky and Commitzen like this video: 

- https://youtu.be/F3B8W3yPPSo
- https://youtu.be/1eTofdmfq1g

**Comment by HelenDias** [comment]
@omariosouto, I saw that there are 2 commits (https://github.com/elvinciqueira/core/commit/fd07dd18da6d51bba764a825dcf13a5e610cc90f and https://github.com/skynexui/core/commit/58abd17403515c80bfeb2cd4127ced5fbee56bdf) about this issue, but it's not in the `main` branch.
Do you still need help with this? If so, I will love to help 😉
