### ISSUE TITLE
I can't execute the examples projects

### ISSUE THREAD

**Issue by Luccasoli** [skynexui/core#23]
i did the steps from here: https://github.com/skynexui/core#contributing, 

but i still getting this error during `yarn install` in monorepo example (in fact, in any of the examples): `error Couldn't find package "@skynexui/native" on the "npm" registry.`

it seems to be the same problem here: https://github.com/yarnpkg/yarn/issues/2611

I'm using yarn 1.22.11 in a Linux Mint OS with node v14.17.5 (in case it is related to the build scripts)

**Comment by omariosouto** [comment]
I believe this solve the problem: https://github.com/skynexui/core/pull/24
